units: units.tsv

genome: "data/genome/all.con"
    
genomelinks:
    ["http://rice.plantbiology.msu.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/all.dir/all.con"]
              
organelle_genomes:
    ["all.con"]

# sequencing adapter
adapter: AGATCGGAAGAGC

params:

    prefetch:
        # ascp: "--ascp-path '/home/kramundson/.aspera/connect/bin/ascp|/home/kramundson/.aspera/connect/etc/asperaweb_id_dsa.openssh' --max-size 50000000000"
        threads: 4

    cutadapt_pe:
        qual: "-q 10 -m 40"
        threads: 8
    
    cutadapt_se:
        qual: "-q 10 -m 40"
        threads: 8
    
    cutadapt_hardtrim:
        qual: "-q 10 -m 40 -l 50"
        threads: 8
    
    align:
        threads: 8
        sort_mem: 4G
    
    mark_duplicates:
        # jarpath: "/share/comailab/kramundson/miniconda3/envs/han/share/picard-2.14.1-0/picard.jar"
        java_heap: "-Xms512m -Xmx4g"
        opt: "REMOVE_DUPLICATES=true TMP_DIR=./tmp ASSUME_SORT_ORDER=coordinate MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000"
    
    bedtools:
        window: 250000
    
    map_qual_filter: "-q 10"

dosage_control:
     - "data/bedtools_coverage/WTA1.bed"

